# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/GitHub/Digital-HWSW-RRI/adc_characterization_fin/adc_characterization_fin.srcs/sources_1/bd/system/ip/system_blk_mem_gen_0_1/system_blk_mem_gen_0_1.xci
# IP: The module: 'system_blk_mem_gen_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GitHub/Digital-HWSW-RRI/adc_characterization_fin/adc_characterization_fin.gen/sources_1/bd/system/ip/system_blk_mem_gen_0_1/system_blk_mem_gen_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_blk_mem_gen_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/GitHub/Digital-HWSW-RRI/adc_characterization_fin/adc_characterization_fin.srcs/sources_1/bd/system/ip/system_blk_mem_gen_0_1/system_blk_mem_gen_0_1.xci
# IP: The module: 'system_blk_mem_gen_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GitHub/Digital-HWSW-RRI/adc_characterization_fin/adc_characterization_fin.gen/sources_1/bd/system/ip/system_blk_mem_gen_0_1/system_blk_mem_gen_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_blk_mem_gen_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
