# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_singletoneFFT/design_singletoneFFT.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_singletoneFFT || ORIG_REF_NAME==design_singletoneFFT} -quiet] -quiet

# IP: bd/design_singletoneFFT/ip/design_singletoneFFT_xfft_0_1/design_singletoneFFT_xfft_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_singletoneFFT_xfft_0_1 || ORIG_REF_NAME==design_singletoneFFT_xfft_0_1} -quiet] -quiet

# IP: bd/design_singletoneFFT/ip/design_singletoneFFT_xlconstant_0_1/design_singletoneFFT_xlconstant_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_singletoneFFT_xlconstant_0_1 || ORIG_REF_NAME==design_singletoneFFT_xlconstant_0_1} -quiet] -quiet

# IP: bd/design_singletoneFFT/ip/design_singletoneFFT_xlconstant_0_2/design_singletoneFFT_xlconstant_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_singletoneFFT_xlconstant_0_2 || ORIG_REF_NAME==design_singletoneFFT_xlconstant_0_2} -quiet] -quiet

# IP: bd/design_singletoneFFT/ip/design_singletoneFFT_xlconstant_2_1/design_singletoneFFT_xlconstant_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_singletoneFFT_xlconstant_2_1 || ORIG_REF_NAME==design_singletoneFFT_xlconstant_2_1} -quiet] -quiet

# IP: bd/design_singletoneFFT/ip/design_singletoneFFT_xlconstant_3_0/design_singletoneFFT_xlconstant_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_singletoneFFT_xlconstant_3_0 || ORIG_REF_NAME==design_singletoneFFT_xlconstant_3_0} -quiet] -quiet

# IP: bd/design_singletoneFFT/ip/design_singletoneFFT_xlconstant_4_0/design_singletoneFFT_xlconstant_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_singletoneFFT_xlconstant_4_0 || ORIG_REF_NAME==design_singletoneFFT_xlconstant_4_0} -quiet] -quiet

# IP: bd/design_singletoneFFT/ip/design_singletoneFFT_c_counter_binary_0_0/design_singletoneFFT_c_counter_binary_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_singletoneFFT_c_counter_binary_0_0 || ORIG_REF_NAME==design_singletoneFFT_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/design_singletoneFFT/ip/design_singletoneFFT_mult_gen_0_0/design_singletoneFFT_mult_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_singletoneFFT_mult_gen_0_0 || ORIG_REF_NAME==design_singletoneFFT_mult_gen_0_0} -quiet] -quiet

# IP: bd/design_singletoneFFT/ip/design_singletoneFFT_xlslice_0_0/design_singletoneFFT_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_singletoneFFT_xlslice_0_0 || ORIG_REF_NAME==design_singletoneFFT_xlslice_0_0} -quiet] -quiet

# IP: bd/design_singletoneFFT/ip/design_singletoneFFT_xlslice_0_1/design_singletoneFFT_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_singletoneFFT_xlslice_0_1 || ORIG_REF_NAME==design_singletoneFFT_xlslice_0_1} -quiet] -quiet

# IP: bd/design_singletoneFFT/ip/design_singletoneFFT_mult_gen_0_1/design_singletoneFFT_mult_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_singletoneFFT_mult_gen_0_1 || ORIG_REF_NAME==design_singletoneFFT_mult_gen_0_1} -quiet] -quiet

# IP: bd/design_singletoneFFT/ip/design_singletoneFFT_c_addsub_0_0/design_singletoneFFT_c_addsub_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_singletoneFFT_c_addsub_0_0 || ORIG_REF_NAME==design_singletoneFFT_c_addsub_0_0} -quiet] -quiet

# IP: bd/design_singletoneFFT/ip/design_singletoneFFT_blk_mem_gen_0_0/design_singletoneFFT_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_singletoneFFT_blk_mem_gen_0_0 || ORIG_REF_NAME==design_singletoneFFT_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/design_singletoneFFT/ip/design_singletoneFFT_c_addsub_0_1/design_singletoneFFT_c_addsub_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_singletoneFFT_c_addsub_0_1 || ORIG_REF_NAME==design_singletoneFFT_c_addsub_0_1} -quiet] -quiet

# IP: bd/design_singletoneFFT/ip/design_singletoneFFT_signal_delay_1_0/design_singletoneFFT_signal_delay_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_singletoneFFT_signal_delay_1_0 || ORIG_REF_NAME==design_singletoneFFT_signal_delay_1_0} -quiet] -quiet

# IP: bd/design_singletoneFFT/ip/design_singletoneFFT_mux_acc_0_0/design_singletoneFFT_mux_acc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_singletoneFFT_mux_acc_0_0 || ORIG_REF_NAME==design_singletoneFFT_mux_acc_0_0} -quiet] -quiet

# IP: bd/design_singletoneFFT/ip/design_singletoneFFT_signal_delay_0_2/design_singletoneFFT_signal_delay_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_singletoneFFT_signal_delay_0_2 || ORIG_REF_NAME==design_singletoneFFT_signal_delay_0_2} -quiet] -quiet

# IP: bd/design_singletoneFFT/ip/design_singletoneFFT_latch_0_0/design_singletoneFFT_latch_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_singletoneFFT_latch_0_0 || ORIG_REF_NAME==design_singletoneFFT_latch_0_0} -quiet] -quiet

# XDC: d:/GitHub/Digital-HWSW-RRI/SingleToneFFT/SingleToneFFT.gen/sources_1/bd/design_singletoneFFT/design_singletoneFFT_ooc.xdc
