# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/GitHub/Digital-HWSW-RRI/SingleToneFFT/SingleToneFFT.srcs/sources_1/bd/design_singletoneFFT/ip/design_singletoneFFT_blk_mem_gen_0_0/design_singletoneFFT_blk_mem_gen_0_0.xci
# IP: The module: 'design_singletoneFFT_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GitHub/Digital-HWSW-RRI/SingleToneFFT/SingleToneFFT.gen/sources_1/bd/design_singletoneFFT/ip/design_singletoneFFT_blk_mem_gen_0_0/design_singletoneFFT_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_singletoneFFT_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/GitHub/Digital-HWSW-RRI/SingleToneFFT/SingleToneFFT.srcs/sources_1/bd/design_singletoneFFT/ip/design_singletoneFFT_blk_mem_gen_0_0/design_singletoneFFT_blk_mem_gen_0_0.xci
# IP: The module: 'design_singletoneFFT_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GitHub/Digital-HWSW-RRI/SingleToneFFT/SingleToneFFT.gen/sources_1/bd/design_singletoneFFT/ip/design_singletoneFFT_blk_mem_gen_0_0/design_singletoneFFT_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_singletoneFFT_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
