# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/nagam/Documents/adc_characterization_fin/adc_characterization_fin/adc_characterization_fin.srcs/constrs_1/imports/cfg/clocks.xdc

# XDC: D:/nagam/Documents/adc_characterization_fin/adc_characterization_fin/adc_characterization_fin.srcs/constrs_1/imports/cfg/ports.xdc

# Block Designs: bd/design_pipeline/design_pipeline.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_pipeline || ORIG_REF_NAME==design_pipeline} -quiet] -quiet

# XDC: d:/GitHub/Digital-HWSW-RRI/DigitalReceiverPipeline/DigitalReceiverPipeline.gen/sources_1/bd/design_pipeline/design_pipeline_ooc.xdc
