# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/GitHub/Digital-HWSW-RRI/DigitalReceiverPipeline/DigitalReceiverPipeline.gen/sources_1/bd/design_pipeline/bd/design_singletoneFFT_inst_1/ip/design_singletoneFFT_inst_1_c_addsub_0_0/design_singletoneFFT_inst_1_c_addsub_0_0.xci
# IP: The module: 'design_singletoneFFT_inst_1_c_addsub_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GitHub/Digital-HWSW-RRI/DigitalReceiverPipeline/DigitalReceiverPipeline.gen/sources_1/bd/design_pipeline/bd/design_singletoneFFT_inst_1/ip/design_singletoneFFT_inst_1_c_addsub_0_0/design_singletoneFFT_inst_1_c_addsub_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_singletoneFFT_inst_1_c_addsub_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/GitHub/Digital-HWSW-RRI/DigitalReceiverPipeline/DigitalReceiverPipeline.gen/sources_1/bd/design_pipeline/bd/design_singletoneFFT_inst_1/ip/design_singletoneFFT_inst_1_c_addsub_0_0/design_singletoneFFT_inst_1_c_addsub_0_0.xci
# IP: The module: 'design_singletoneFFT_inst_1_c_addsub_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GitHub/Digital-HWSW-RRI/DigitalReceiverPipeline/DigitalReceiverPipeline.gen/sources_1/bd/design_pipeline/bd/design_singletoneFFT_inst_1/ip/design_singletoneFFT_inst_1_c_addsub_0_0/design_singletoneFFT_inst_1_c_addsub_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_singletoneFFT_inst_1_c_addsub_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
