# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/GitHub/Digital-HWSW-RRI/DigitalReceiverPipeline/DigitalReceiverPipeline.gen/sources_1/bd/design_pipeline/bd/system_inst_0/ip/system_inst_0_rst_ps7_0_125M_0/system_inst_0_rst_ps7_0_125M_0.xci
# IP: The module: 'system_inst_0_rst_ps7_0_125M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GitHub/Digital-HWSW-RRI/DigitalReceiverPipeline/DigitalReceiverPipeline.gen/sources_1/bd/design_pipeline/bd/system_inst_0/ip/system_inst_0_rst_ps7_0_125M_0/system_inst_0_rst_ps7_0_125M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_inst_0_rst_ps7_0_125M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/GitHub/Digital-HWSW-RRI/DigitalReceiverPipeline/DigitalReceiverPipeline.gen/sources_1/bd/design_pipeline/bd/system_inst_0/ip/system_inst_0_rst_ps7_0_125M_0/system_inst_0_rst_ps7_0_125M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_inst_0_rst_ps7_0_125M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/GitHub/Digital-HWSW-RRI/DigitalReceiverPipeline/DigitalReceiverPipeline.gen/sources_1/bd/design_pipeline/bd/system_inst_0/ip/system_inst_0_rst_ps7_0_125M_0/system_inst_0_rst_ps7_0_125M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_inst_0_rst_ps7_0_125M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/GitHub/Digital-HWSW-RRI/DigitalReceiverPipeline/DigitalReceiverPipeline.gen/sources_1/bd/design_pipeline/bd/system_inst_0/ip/system_inst_0_rst_ps7_0_125M_0/system_inst_0_rst_ps7_0_125M_0.xci
# IP: The module: 'system_inst_0_rst_ps7_0_125M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GitHub/Digital-HWSW-RRI/DigitalReceiverPipeline/DigitalReceiverPipeline.gen/sources_1/bd/design_pipeline/bd/system_inst_0/ip/system_inst_0_rst_ps7_0_125M_0/system_inst_0_rst_ps7_0_125M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_inst_0_rst_ps7_0_125M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/GitHub/Digital-HWSW-RRI/DigitalReceiverPipeline/DigitalReceiverPipeline.gen/sources_1/bd/design_pipeline/bd/system_inst_0/ip/system_inst_0_rst_ps7_0_125M_0/system_inst_0_rst_ps7_0_125M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_inst_0_rst_ps7_0_125M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/GitHub/Digital-HWSW-RRI/DigitalReceiverPipeline/DigitalReceiverPipeline.gen/sources_1/bd/design_pipeline/bd/system_inst_0/ip/system_inst_0_rst_ps7_0_125M_0/system_inst_0_rst_ps7_0_125M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_inst_0_rst_ps7_0_125M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
